# This is used to run the app locally
version: '3.7'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: npm run local_dev_dc
    restart: unless-stopped
    working_dir: /app
    volumes: 
    - ./:/app
    - node_modules:/app/node_modules
    ports:
    - 4200:4200
    environment: 
      production: "False"
      FYLE_CLIENT_ID: tpaYfU7VLyrEN
      API_URL: http://localhost:8003/api
      APP_URL: http://localhost:4200
      OLD_XERO_APP_URL: http://localhost:4201/auth/shared_login
      CALLBACK_URI: http://localhost:4200/auth/callback
      XERO_CLIENT_ID: BB139467D5424B14BE3DBF92895EB6CF
      XERO_SCOPE: accounting.transactions accounting.settings accounting.contacts offline_access accounting.attachments
      XERO_AUTHORIZE_URI: https://login.xero.com/identity/connect/authorize
      SENTRY_DSN: ''
      SENTRY_ENV: ''
      RELEASE: 'local'
      FYLE_APP_URL: https://app.fyle.tech
      TESTS_WORKSPACEID: 1
      REFINER_ONBOARDING_DONE_SURVEY_ID: 
      REFINER_EXPORT_DONE_SURVEY_ID: 

volumes:
  node_modules: