name: Codecov Report Upload

on:
  push:
    branches:
      - master
  pull_request:
    types: [labeled]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: TypeScript Lint GitHub Action
      uses: actions/setup-node@v1
      with:
        node-version: 14.18
    - name: Install dependencies
      run: npm install
    - name: Test
      run: npm run unit_test_ci
      env:
        FYLE_CLIENT_ID: ${{secrets.FYLE_CLIENT_ID}} 
        CALLBACK_URL: ${{secrets.CALLBACK_URL}} 
        API_URL: ${{secrets.API_URL}} 
        APP_URL: ${{secrets.APP_URL}} 
        XERO_CLIENT_ID: ${{secrets.XERO_CLIENT_ID}} 
        XERO_SCOPE: ${{secrets.XERO_SCOPE}} 
        XERO_AUTHORIZE_URI: ${{secrets.XERO_AUTHORIZE_URI}} 
        SENTRY_DSN: ${{secrets.SENTRY_DSN}} 
        RELEASE: ${{secrets.RELEASE}} 
        FYLE_APP_URL: ${{secrets.FYLE_APP_URL}} 
        TESTS_WORKSPACEID: ${{secrets.TESTS_WORKSPACEID}}
        XERO_CALLBACK_URI: ${{secrets.XERO_CALLBACK_URI}}
    - name: Comment Test Coverage
      uses: AthleticNet/comment-test-coverage@1.2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: coverage/coverage-summary.json
        title: Karma Test Coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
